[package]
name = "oq-imgcomp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
reqwest = "0.11"
image = "0.24.2"
ravif = "0.11.2"
rgb = "0.8.36"
bytes = "1.1.0"
exif = { version = "0.5.5", package = "kamadak-exif" }
